
# For more information on GitHub Actions, refer to https://github.com/features/actions
# For a complete CI/CD sample to get started with GitHub Action workflows for Desktop Applications,
# refer to https://github.com/microsoft/github-actions-for-desktop-apps

name: CI Pipeline for SwagLabsTestProject

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest  # Możesz wybrać inną wersję systemu, np. windows-latest
    
    steps:
      # Krok 1: Checkout kodu
      - name: Checkout code
        uses: actions/checkout@v2

      # Krok 2: Zainstaluj .NET SDK
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'  # Użyj odpowiedniej wersji .NET

      # Krok 3: Build aplikacji .NET
      - name: Build .NET application
        run: |
          dotnet restore
          dotnet build --configuration Release

      # Krok 4: Uruchom Docker Compose
      - name: Set up Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d  # Załóżmy, że masz docker-compose.yml w repozytorium

      # Krok 5: Uruchom testy
      - name: Run .NET tests
        run: |
          dotnet test

      # Krok 6: Zatrzymaj kontener Docker po testach
      - name: Tear down Docker Compose
        run: |
          docker-compose down

      # Krok 7: Przeprowadź działania na Dockerze lub wydanie, jeśli testy się powiodą
      # Możesz dodać tutaj kolejne kroki w zależności od potrzeby (np. wdrożenie)
